import Head from 'next/head'
import Image from 'next/image'

import FirstSection from './../component/FirstSection'
import QuestionSection from './../component/QuestionSection'
import ThirdSection from './../component/ThirdSection'
import ForthSection from './../component/ForthSection'
import FifthSection from './../component/FifthSection'
import SixthSection from './../component/SixthSection'
import QAsection from './../component/Q&Asection'
import Footer from './../component/Footer'
import Navbar from './../component/Navbar'
import styled from 'styled-components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>F2E</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main >
       <>
      <section style={{width: '1440px', margin: "0 auto"}}>
        <Navbar />
      </section>
      <FirstSection />
      <QuestionSection />
      <ThirdSection />
      <ForthSection />
      <FifthSection />
      <SixthSection />
      <QAsection />
      <Footer />
    </>

      </main>


    </div>
  )
}
